name: Workflow Inicial
on: push

jobs:
    job1-hello:
        runs-on: ubuntu-latest
        steps:
        - name: Imprimir mensagem
          run: echo "Inicialização"
    job2-goodbye:
        runs-on: ubuntu-latest
        steps:
        - name: Step 1 - Sequencia de instruções
          run: |
            echo "Testando instruções do GitHub WorkFlows"
            ls            
        - name: Step 2 - Imprimir mensagem
          run: echo "Finalizado!"